name: ChunkLoad
main: com.github.nidan.chunkload.ChunkLoadPlugin
version: 0.4.1
depend: [WorldEdit]
commands:
    chunkload:
       aliases: [cl]
       description: The ChunkLoad command.
       usage: /<command> list [page]|select <name>|add <name>|remove <name>|reload
permissions:
    chunkload.usage:
        description: Allows usage of ChunkLoad 
        default: op
